import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#002113",
        "primary-container": "#1c1b1b",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#822800",
        "on-tertiary-container": "#45926e",
        "on-background": "#1e1b16",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "tertiary": "#000000",
        "surface-bright": "#fff8f0",
        "secondary-container": "#fe7440",
        "surface": "#fff8f0",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-primary": "#c8c6c5",
        "secondary": "#a93702",
        "outline-variant": "#c4c7c7",
        "surface-dim": "#dfd9d0",
        "outline": "#747878",
        "surface-container": "#f4ede4",
        "error": "#ba1a1a",
        "on-surface-variant": "#444748",
        "on-secondary-fixed": "#380c00",
        "surface-container-high": "#eee7de",
        "on-error": "#ffffff",
        "inverse-surface": "#33302a",
        "surface-container-low": "#f9f3ea",
        "on-tertiary-fixed": "#002113",
        "on-primary-container": "#858383",
        "secondary-fixed": "#ffdbcf",
        "primary": "#000000",
        "primary-fixed": "#e5e2e1",
        "surface-container-highest": "#e8e2d9",
        "on-secondary-container": "#641c00",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#a4f3c9",
        "on-primary-fixed-variant": "#474746",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#89d6ae",
        "inverse-on-surface": "#f6f0e7",
        "surface-variant": "#e8e2d9",
        "on-surface": "#1e1b16",
        "secondary-fixed-dim": "#ffb59c",
        "primary-fixed-dim": "#c8c6c5",
        "background": "#fff8f0",
        "on-primary-fixed": "#1c1b1b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "1.25rem",
        "margin-desktop": "3rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.75rem",
        "space-sm": "0.5rem",
        "margin-tablet": "2rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin": "1rem"
      },
      fontFamily: {
        "display-md": ["var(--font-newsreader)"],
        "body-lg": ["var(--font-manrope)"],
        "display-md-mobile": ["var(--font-newsreader)"],
        "headline-md": ["var(--font-manrope)"],
        "label-sm": ["var(--font-manrope)"],
        "headline-sm": ["var(--font-manrope)"],
        "display-lg": ["var(--font-newsreader)"],
        "headline-lg": ["var(--font-manrope)"],
        "label-md": ["var(--font-manrope)"],
        "body-sm": ["var(--font-manrope)"],
        "mono-spec": ["var(--font-manrope)"],
        "body-md": ["var(--font-manrope)"],
        "display-lg-mobile": ["var(--font-newsreader)"],
        "label-lg": ["var(--font-manrope)"]
      },
      fontSize: {
        "display-md": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "0", "fontWeight": "400" }],
        "display-md-mobile": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-md": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "mono-spec": ["11px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0", "fontWeight": "400" }],
        "display-lg-mobile": ["38px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
