import { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";
import { LEGAL_CONFIG } from "@/lib/legal-config";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "Important information regarding the use of ToolKB's output and generated files for third-party submissions.",
  alternates: {
    canonical: `${LEGAL_CONFIG.DOMAIN}/disclaimer`,
  },
};

export default function Disclaimer() {
  return (
    <LegalLayout title="Disclaimer" lastUpdated={LEGAL_CONFIG.LAST_UPDATED}>
      <section className="space-y-4">
        <h2 className="text-title-lg font-bold text-on-surface">General Purpose Utilities</h2>
        <p>
          {LEGAL_CONFIG.SITE_NAME} provides general-purpose utilities designed to help users compress, resize, and manage image files. While we strive for accuracy and reliability in our tools, the generated files are provided &quot;as is.&quot;
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-title-lg font-bold text-on-surface">Third-Party Requirements</h2>
        <p>
          <strong>{LEGAL_CONFIG.SITE_NAME} does not guarantee that a file produced by our tools will satisfy every external requirement.</strong> 
        </p>
        <p>
          Users often process files for submission to third-party portals, which may include:
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Government or official application portals</li>
          <li>Examination and academic admission authorities</li>
          <li>University enrollment systems</li>
          <li>Banks and financial institutions</li>
          <li>Visa, passport, and immigration services</li>
          <li>Recruitment and employment platforms</li>
        </ul>
        <p>
          These systems frequently enforce strict rules regarding:
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Exact file size limits (e.g., &quot;strictly under 50KB&quot;)</li>
          <li>Exact pixel dimensions or aspect ratios</li>
          <li>Specific formats and metadata profiles</li>
          <li>Required DPI or image resolution</li>
        </ul>
        <p>
          <strong>You are solely responsible</strong> for verifying the exact requirements of the destination service and ensuring the output file generated by {LEGAL_CONFIG.SITE_NAME} meets those criteria before submission.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-title-lg font-bold text-on-surface">No Affiliation or Endorsement</h2>
        <p>
          {LEGAL_CONFIG.SITE_NAME} is an independent, private utility. We are <strong>not affiliated with</strong>, partnered with, or endorsed by any government agencies, universities, banks, recruitment portals, examination authorities, or other third-party organizations. 
        </p>
        <p>
          Any mention on our website of specific use-cases (e.g., &quot;compressing a photo for a job application&quot;) is provided purely as practical context for our users, and does not imply sponsorship, certification, or an official relationship with the organizations receiving the applications.
        </p>
      </section>

      {LEGAL_CONFIG.CONTACT_EMAIL && (
        <section className="space-y-4">
          <h2 className="text-title-lg font-bold text-on-surface">Questions</h2>
          <p>
            If you have questions about this disclaimer, contact us at: <a href={`mailto:${LEGAL_CONFIG.CONTACT_EMAIL}`} className="text-primary hover:underline">{LEGAL_CONFIG.CONTACT_EMAIL}</a>
          </p>
        </section>
      )}
    </LegalLayout>
  );
}
